### ISSUE TITLE
Add option to choose which side of text in the button the spinner shows up in

### ISSUE THREAD

**Issue by feiwaltan** [yury-dymov/react-bootstrap-button-loader#2]
Is it possible to add an option to configure the spinner location? either float left or float right?

supporting the bootstrap style ``//` Classes
.pull-left {
  float: left !important;
}
.pull-right {
  float: right !important;
}`

If the outer div style for in the `Spinner.jsx` added the `float: right !important` or `float: left !important` with some padding, it would allow us to choose which side of the text the spinner shows up.

**Comment by yury-dymov** [comment]
@feiwaltan this is not supported as for now but can be easily extended. You may file a PR and I will either merge or help to make it production-ready.

**Comment by feiwaltan** [comment]
@yury-dymov can you provide some instructions on how to contribute to the project? I'd like to add this ability and need some guidance on building and testing out the update.

**Comment by yury-dymov** [comment]
@feiwaltan should pretty straightforward, you need patch https://github.com/yury-dymov/react-bootstrap-button-loader/blob/master/src/ButtonLoader.jsx by adding a prop, which would apply a desired style to the Spinner element if equals true

**Comment by feiwaltan** [comment]
@yury-dymov do I need branch creation permission to be able to contribute? I've got changes ready to commit to the two files that would be modified.

**Comment by yury-dymov** [comment]
1. fork the project
2. start your branch in your repo
3. add some commits
4. create a pull request from your branch to my repo on the github
5. I will review and ask for more changes or merge right away
