### ISSUE TITLE
Update react loader version?

### ISSUE THREAD

**Issue by Alameli** [yury-dymov/react-bootstrap-button-loader#6]
react-loader is currently set at 2.4.2 in this project but the react-loader repo has been updated to 2.4.5 which supports react 16.

It'd also clear up any npm dependencies warning as well.

**Comment by yury-dymov** [comment]
Hey @Alameli,

Sure, feel free to fire a PR.

Best regards,
Yury

**Comment by Alameli** [comment]
PR at #7
