### ISSUE TITLE
failed to compile 

### ISSUE THREAD

**Issue by syrakozz** [yury-dymov/react-bootstrap-button-loader#8]
i got 
./node_modules/react-bootstrap-button-loader/dist/index.js
Module not found: Can't resolve 'react-bootstrap/lib/Button' 

iam using reactsrap with it

**Comment by yury-dymov** [comment]
`react-bootstrap` is a peer dependency for this package. Either you need to install it `npm install --save react-bootstrap`, or this package is not suitable for you

**Comment by syrakozz** [comment]
thank you i converted to user reactsrap
