### ISSUE TITLE
Button Component Moved In React Bootstrap

### ISSUE THREAD

**Issue by reggie3** [yury-dymov/react-bootstrap-button-loader#9]
I received the following error trying to use this package Module not found: Can't resolve 'react-bootstrap/lib/Button'

Looking through my node modules directory I saw that the Button component is no longer in lib, and is actually in the react-bootstrap root directory

![image](https://user-images.githubusercontent.com/7347192/58386890-2611b600-7fd4-11e9-9430-a5855dd6743b.png)

I'm using the following package versions:

```
   "react-bootstrap": "^1.0.0-beta.8",
    "react-bootstrap-button-loader": "^1.0.12",
```

**Comment by yury-dymov** [comment]
I am going to support react-bootstrap 1.0.0 once it is released (currently beta)

**Comment by broofa** [comment]
This module is currently broken for the default install of react-bootstrap (`npm install react-bootstrap` installs 1.0.0-beta.9) .  Standard practice in this situation would be:

1. Keep this issue open until a fix is available
2. Fix this issue, and release as a major version update (breaks backward compatibility)
